name: Weekly Submodule Updates

on:
  schedule:
    - cron: '0 0 * * 0'  # Runs every Sunday at midnight (UTC)
  workflow_dispatch:     # Optional: Allow manual trigger

jobs:
  update-submodules:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # Needed to push changes

    steps:
      # 1. Checkout repo + submodules
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          fetch-depth: 0  # Required for proper Git history

      # 2. Update all submodules to latest main (--remote follows branch defined in .gitmodules)
      - name: Update Submodules
        run: |
          git submodule update --remote --merge
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      # 3. Commit & Push (if changes detected)
      - name: Commit and Push Updates
        run: |
          if git diff --quiet --exit-code; then
            echo "No submodule updates found."
          else
            git add .
            git commit -m "chore: weekly submodule updates [automated]"
            git push
            echo "Pushed submodule updates."
          fi
